### ISSUE TITLE
Consider using IActionConstraint to toggle actions

### ISSUE THREAD

**Issue by rynowak** [Xabaril/Xabaril#6]
Hi,

I'm one of the developers working on aspnet/MVC. Someone shared this link with me and what you have here looks pretty cool!

One idea that I have for you is that if you want to toggle **between** two different versions of an action method, you can use `IActionConstraint` to accomplish this. An example of how this might work:

```
public class SomeController : Controller
{
    public IActionResult SomeAction() { }

    [ActionName("SomeAction")]
    [ActiveForFeature("SomeFeature")]
    public IActionResult SomeActionWithExtraFeature() { }
}
```

The presence of `ActiveForFeatureAttribute` on `SomeActionWithExtraFeature` makes it a preferred choice when multiple actions match. If the feature is disabled, the `ActiveForFeatureAttribute` rejects the request (similar to `FeatureFilter` and the action selector will choose `SomeAction` instead.

`ActiveForFeatureAttribute` would implement `IActionConstraint` or `IActionConstraintFactory`. See an example here: https://github.com/aspnet/Mvc/blob/dev/test/WebSites/VersioningWebSite/

The only wrinkle you'd have here is that `IActionConstraints` are synchronous, and we have no plans to make them async.

**Comment by unaizorrilla** [comment]
Hi Ryan....

Many thanks for this idea, pretty cool... I try to work on this right now!

**Comment by unaizorrilla** [comment]
Closed with https://github.com/Xabaril/Xabaril/commit/971582b2bbf673c0f8997f6acbf79dab9e461219

**Comment by rynowak** [comment]
Pretty cool, thanks!
